- name: Add Jessie Backports repository
  apt_repository:
    repo: deb http://ftp.debian.org/debian jessie-backports main
    state: present
  register: jessie_repository_added

- name: ensure letsencrypt installed
  apt:
    name: letsencrypt
    state: present
    default_release: jessie-backports
    update_cache: yes
  when: jessie_repository_added.changed

- name: Check if certificate already exists.
  stat:
    path: '/etc/letsencrypt/live/{{ web_hostname }}/cert.pem'
  register: letsencrypt_cert

- name: Generate new certificate if one doesn't exist.
  shell: 'certbot certonly --standalone --agree-tos -n -m {{ registration_email }} -d {{ web_hostname }} --pre-hook "systemctl stop nginx" --post-hook "systemctl start nginx"'
  when: not letsencrypt_cert.stat.exists

- name: ensure ssl file exists
  copy:
    content: |
      listen 443 ssl http2;
      ssl_certificate /etc/letsencrypt/live/{{ web_hostname }}/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/{{ web_hostname }}/privkey.pem;
    dest: "/etc/nginx/conf.d/{{ web_hostname }}.https.include"
  register: https_include

- name: reload nginx service
  systemd:
    name: nginx
    state: reloaded
  when: https_include.changed

- name: Add cron job for certbot renewal
  cron:
    name: "Certbot automatic renewal"
    job: /usr/bin/certbot renew --pre-hook "systemctl stop nginx" --post-hook "systemctl start nginx" --agree-tos -n --no-self-upgrade
    minute: "5"
    hour: "5"
    user: root
