
- name: ensure upstream file exists
  copy:
    content: |
      set $git_work_endpoint http://127.0.0.1:{{ upstream_port }};
    dest: "/etc/nginx/conf.d/{{ web_hostname }}.upstreams.include"

- name: ensure ssl file exists
  file:
    path: "/etc/nginx/conf.d/{{ web_hostname }}.https.include"
    state: touch

- name: copy nginx template configuration
  template: >
    src=git-work.nginx.conf.j2
    dest=/etc/nginx/conf.d/{{ web_hostname }}.conf
    mode=0755

- name: reload nginx service
  systemd:
    name: nginx
    state: reloaded
