---

- name: NGINX | Add signing key to use sources
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: NGINX | Add sources to install nginx
  apt_repository:
    repo: deb http://nginx.org/packages/mainline/debian/ jessie nginx
    state: present
  register: new_repo

- name: NGINX | Install nginx
  apt:
    package: nginx=1.13.*
    state: present
    update_cache: yes
  when: new_repo.changed

- name: NGINX | Unmask NGINX
  service:
    name: nginx
    masked: no

- name: NGINX | Enable NGINX
  service:
    name: nginx
    enabled: yes

- name: Disable the default site
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: NGINX | Start NGINX
  service:
    name: nginx
    state: started
