---
- hosts: allx
  become: yes
  roles:
    - role: git-work-nginx

- hosts: all
  become: yes
  roles:
     - role: git-work-instance
       instance_port: 12345
       instance_dir: /home/git-work/blue
       user: git-work
       service_name: git-work-blue
