---

- hosts: all
  tags:
    - debug
  tasks:
    - name: DEBUG - print host names
      debug:
        msg="Host {{ ansible_hostname }} has inventory hostname {{ inventory_hostname }}, has uuid {{ ansible_product_uuid }}"
    - name: DEBUG - print host vars
      debug: msg="h = {{ web_hostname }}"

- hosts: all
  tags:
    - setup
  tasks:
  - hostname:
      name: git.work

- hosts: all
  tags:
    - nginx
  become: yes
  roles:
    - role: git-work-nginx

- hosts: all
  become: yes
  tags:
    - ssl
  roles:
    - role: git-work-nginx-ssl

- hosts: all
  become: yes
  tags:
    - instance
  roles:
    - role: git-work-instance
      instance_port: 12345
      instance_dir: /home/git-work/blue
      user: git-work
      service_name: git-work-blue
    - role: git-work-instance
      instance_port: 12346
      instance_dir: /home/git-work/green
      user: git-work
      service_name: git-work-green
