---
- hosts: git.work
  tags:
    - setup
  tasks:
  - hostname:
      name: git.work
  - apt:
      pkg: nginx
      state: present

- hosts: all
  tags:
    - nginx
  become: yes
  roles:
    - role: git-work-nginx

- hosts: all
  become: yes
  tags:
    - ssl
  roles:
    - role: git-work-nginx-ssl

- hosts: all
  become: yes
  tags:
    - instance
  roles:
    - role: git-work-instance
      instance_port: 12345
      instance_dir: /home/git-work/blue
      user: git-work
      service_name: git-work-blue
    - role: git-work-instance
      instance_port: 12346
      instance_dir: /home/git-work/green
      user: git-work
      service_name: git-work-green
