Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 1536
    v.cpus = 2
  end

  config.vm.network "forwarded_port", guest: 80, host: 8111
    config.vm.provision :shell, :inline => "ulimit -n 4048"
   config.vm.box = "debian/jessie64"
  #config.vm.box = "freebsd/FreeBSD-11.0-STABLE"

  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/mitchellh/vagrant/issues/5005
  config.ssh.insert_key = false
  #config.vm.provision "shell",
#    inline: "pkg install -y python"
end
