- name: Set up git-work user
  become: yes
  user:
    name: "{{ user }}"

- name: ensure git installed
  become: yes
  package:
    name: git
    state: present

- name: ensure jdk8 is installed
  become: yes
  package:
    name: java-1.8.0-openjdk
    state: present

- name: Add SBT repository
  yum_repository:
    name: sbt
    description: SBT repo
    baseurl: http://sbt.bintray.com/rpm
    gpgcheck: no

- name: ensure sbt is installed
  become: yes
  package:
    name: sbt
    state: present

- name: checkout repo
  git: "repo=https://github.com/ScalaWilliam/git-work.git version=master dest={{ local_repository }}"
  become: yes
  become_user: {{ user }}

- name: Creates directory
  file: "path={{ instance_dir }} state=directory"
  become: true
  become_user: {{ user }}

- name: copy systemd service template configuration
  template: >
    src=git-work.service.j2
    dest="/etc/systemd/system/{{ service_name }}.service"
    mode=0755
  register: gws

- name: reload systemd
  systemd:
    name: "{{ service_name }}"
    daemon_reload: yes
  when: gws.changed

- name: Check if it's been deployed
  stat: "path={{ instance_dir }}/bin/git-work"
  register: check_git_work

- name: Deploy Git Work without restarting
  shell: "cd {{ local_repository }} && DESTDIR={{ instance_dir }} ./push deploy-app"
  become: true
  become_user: "{{ user }}"
  when: check_git_work.stat.exists == false
  register: deployed

- name: restart and enable the service
  systemd:
    name: "{{ service_name }}"
    state: restarted
    enabled: yes
  when: gws.changed or (deployed is defined)

- name: copy nginx template configuration
  template: >
    src=git-work.nginx.conf.j2
    dest=/etc/nginx/conf.d/git-work.conf
    mode=0755
  register: gwn

- name: reload nginx service
  systemd:
    name: nginx
    state: reloaded
  when: gwn.changed

