
- name: ensure ssl file exists
  file:
    path: "/etc/nginx/conf.d/www.{{ naked_hostname }}.https.include"
    state: touch

- name: copy nginx template configuration
  template: >
    src=redirect.nginx.conf.j2
    dest=/etc/nginx/conf.d/redirect-{{ naked_hostname }}.conf
    mode=0755

- name: reload nginx service
  systemd:
    name: nginx
    state: reloaded
